Communities save in Realm, added observe
tonarisun/LittleSocialMedia pull request #6
Opened 2019-05-23 06:16 UTC by tonarisun

Я сделала observe только для групп, вроде нужно было всё, но друзей я трогать боюсь, если честно) несколько дней потратила на них, чтобы отображались нормально и поиск работал, теперь просто страшно что-то сломать...) на контроллере с моими группами (MyCommunityController) поиск работает не корректно, подскажи, пожалуйста, как сделать правильно (проблема с большими буквами в самих названиях групп, как сделать их lowercased). На контроллере с глобальным поиском групп тоже не вполне хорошо работает.. починю постепенно))

2019-05-23 14:17 UTC, Antol requested changes

2019-05-23 14:17 UTC, Antol commented on Weather/Communities/MyCommunityController.swift
> +                self?.addRealmObserve()
Ну про это я тебе в личке писал

2019-05-24 11:38 UTC, tonarisun commented on Weather/Communities/MyCommunityController.swift
> +                self?.addRealmObserve()
А про поиск можешь подсказать?
        filteredMyCommunities = myCommunities?.filter("communityName CONTAINS '\(searchText.lowercased())'") // Как сделать, чтобы communityName был тоже lowercased?

2019-05-24 14:04 UTC, tonarisun commented on Weather/Communities/MyCommunityController.swift
> +                self?.addRealmObserve()
filteredMyCommunities = myCommunities?.filter("communityName CONTAINS '\(searchText.lowercased())'")
как вот тут сделать lowercased, ведь мы обращаемся через строку?

2019-05-25 02:51 UTC, merged